### ISSUE TITLE
XEP-0363 vs XEP-0065

### ISSUE THREAD

**Issue by o---** [iNPUTmice/caas#107]
A server is not considered as fully compliant when it does not support XEP-0065. 
But there are other methods of file transfer, such as XEP-0363. 
The result is the same - clients can exchange files + transfer is much faster and not depended on recipients "online status".

**Comment by licaon-kter** [comment]
Yes, different XEPs, useful for some but not for you. Ok, and?

**Comment by o---** [comment]
> Yes, different XEPs, useful for some but not for you. Ok, and?

Some have understood the suggestion to accept alternate XEP's, but not you. And now?

**Comment by licaon-kter** [comment]
I don't understand why you opened this exactly, what's the "issue"?

**Comment by o---** [comment]
I am suggesting to accept a server as compliant even if it uses one of the suitable alternative XEP's. As long as _the functionality_ (covered **for example** by the XEP-0065) is provided to it's users by some other XEP (**in this example** XEP-0363).

**Comment by iNPUTmice** [comment]
Those two XEPs complement each other. P2P file transfer is used automatically for larger files.
