### ISSUE TITLE
No live tests running

### ISSUE THREAD

**Issue by steffanson** [iNPUTmice/caas#15]
It is not possible to rerun a test for this particular server:

1) Go to `https://compliance.conversations.im/server/chat.mass-trespass.uk/`
2) Click on rerun test
3) `https://compliance.conversations.im/live/chat.mass-trespass.uk/` opens and says:

> Running tests for chat.mass-trespass.uk
> No live tests running for chat.mass-trespass.uk. Try refreshing this page

All other servers I tried can be manually tested again.

**Comment by RishiRaj22** [comment]
This error message gets shown only if the tests complete before the web socket connection gets established between the browser and server for listening to the result. Most probably the XMPP server is not available as if it were available, it would definitely require some time to run the tests. I will do some refactoring in the weekends to ensure correct error message gets shown.
