### ISSUE TITLE
Tests s2s connections between every xmpp server

### ISSUE THREAD

**Issue by genofire** [iNPUTmice/caas#17]
TThis would be really nice

**Comment by iNPUTmice** [comment]
You can use [status.conversations.im](https://status.conversations.im) for that. I don’t think this has anything to do with compliance and is not the right fit for the Compliance Tester.

**Comment by genofire** [comment]
How could a add my server

**Comment by genofire** [comment]
Okay found by reading sourcode: https://status.conversations.im/add/ ;(
