### ISSUE TITLE
Building the command line tool fails

### ISSUE THREAD

**Issue by herrwusel** [iNPUTmice/caas#20]
After `mvn package` in `/caas-app` like described [here](https://github.com/iNPUTmice/caas#build-instructions):

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.274 s
[INFO] Finished at: 2018-10-14T11:40:06+02:00
[INFO] Final Memory: 7M/34M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project caas-app: Could not resolve dependencies for project im.conversations.compliance:caas-app:jar:0.0.1: Failure to find im.conversations.compliance:caas-annotations:jar:0.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Building the entire package is working.
OS: Kubuntu 18.04
Java: 11
maven: 3.5.2-2

**Comment by RishiRaj22** [comment]
Can you try to run mvn install in caas-annotations folder and then try it?

**Comment by herrwusel** [comment]
Did it and error still occurs.

**Comment by alexara** [comment]
I can confirm it with the same setup, however building both the command line tool and web service by simply running `mvn package` from the root directory works.

**Comment by iNPUTmice** [comment]
> Can you try to run mvn install in caas-annotations folder and then try it?

You probably need to install that one first. But I think it will be so much easier if you just build the top level project.
