### ISSUE TITLE
Message: Premature end of file.

### ISSUE THREAD

**Issue by froghorn82** [iNPUTmice/caas#25]
Hello,

When testing omemo.im the following error appears. Testing was working fine previously.

Running tests for omemo.im
ParseError at [row,col]:[1,1] Message: Premature end of file.

**Comment by froghorn82** [comment]
anybody?

**Comment by RishiRaj22** [comment]
Can you run the command line tool and give the complete log?

**Comment by froghorn82** [comment]
`Use compliance suite 'Advanced Server Core Compliance Suite' to test omemo.im

javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.


Use compliance suite 'Advanced Server IM Compliance Suite' to test omemo.im

javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.


Use compliance suite 'Advanced Server Mobile Compliance Suite' to test omemo.im

javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.


Use compliance suite 'Conversations Compliance Suite' to test omemo.im

javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.`

**Comment by froghorn82** [comment]
@iNPUTmice can you please help with this.

**Comment by licaon-kter** [comment]
Can you make an account on a random free server and test against that?

**Comment by froghorn82** [comment]
works perfectly fine on a free random server - i tested creep.

`java -jar ComplianceTester-0.2.3.jar randomness@creep.im 123
Use compliance suite 'Advanced Server Core Compliance Suite' to test creep.im

running XEP-0115: Entity Capabilities…		PASSED
running XEP-0163: Personal Eventing Protocol…		PASSED
passed 2/2

Advanced Server Core Compliance Suite: PASSED


Use compliance suite 'Advanced Server IM Compliance Suite' to test creep.im

running XEP-0115: Entity Capabilities…		PASSED
running XEP-0163: Personal Eventing Protocol…		PASSED
running Roster Versioning…		PASSED
running XEP-0280: Message Carbons…		PASSED
running XEP-0191: Blocking Command…		PASSED
running XEP-0045: Multi-User Chat…		PASSED
running XEP-0198: Stream Management…		PASSED
running XEP-0313: Message Archive Management…		PASSED
passed 8/8

Advanced Server IM Compliance Suite: PASSED


Use compliance suite 'Advanced Server Mobile Compliance Suite' to test creep.im

running XEP-0115: Entity Capabilities…		PASSED
running XEP-0163: Personal Eventing Protocol…		PASSED
running XEP-0198: Stream Management…		PASSED
running XEP-0352: Client State Indication…		PASSED
running XEP-0357: Push Notifications…		PASSED
passed 5/5

Advanced Server Mobile Compliance Suite: PASSED


Use compliance suite 'Conversations Compliance Suite' to test creep.im

Server is ejabberd 18.09-1~afa90
running XEP-0115: Entity Capabilities…		PASSED
running XEP-0163: Personal Eventing Protocol…		PASSED
running Roster Versioning…		PASSED
running XEP-0280: Message Carbons…		PASSED
running XEP-0191: Blocking Command…		PASSED
running XEP-0045: Multi-User Chat…		PASSED
running XEP-0198: Stream Management…		PASSED
running XEP-0313: Message Archive Management…		PASSED
running XEP-0352: Client State Indication…		PASSED
running XEP-0363: HTTP File Upload…		PASSED
running XEP-0065: SOCKS5 Bytestreams (Proxy)…		PASSED
running XEP-0357: Push Notifications…		PASSED
running XEP-0368: SRV records for XMPP over TLS…		PASSED
running XEP-0384: OMEMO Encryption…		PASSED
running XEP-0313: Message Archive Management (MUC)…		PASSED
passed 15/15

Conversations Compliance Suite: PASSED`

**Comment by licaon-kter** [comment]
@froghorn82 why are you running the *old* compliance tester?

You need to compile *caas* from here and use it: https://github.com/iNPUTmice/caas/

**Comment by froghorn82** [comment]
ok compiled as mentioned. here are my results from both creep.im (which works) and omemo.im (same error)

java -jar caas-app/target/caas-app.jar randomness@creep.im 123
Server is running ejabberd 18.09-1~afa90

Compliance report for creep.im
XEP-0398: User Avatar to vCard-Based Avatars Conversion          PASSED
XEP-0045: Multi-User Chat                                        PASSED
XEP-0363: HTTP File Upload                                       PASSED
XEP-0384: OMEMO Encryption                                       PASSED
XEP-0313: Message Archive Management                             PASSED
XEP-0313: Message Archive Management (for Multi-User Chat)       PASSED
XEP-0065: SOCKS5 Bytestreams (Proxy)                             PASSED
XEP-0280: Message Carbons                                        PASSED
XEP-0352: Client State Indication                                PASSED
XEP-0198: Stream Management                                      PASSED
XEP-0115: Entity Capabilities                                    PASSED
Roster Versioning                                                PASSED
XEP-0191: Blocking Command                                       PASSED
XEP-0163: Personal Eventing Protocol                             PASSED
XEP-0357: Push Notifications                                     PASSED
XEP-0160: Best Practices for Handling Offline Messages           PASSED
XEP-0368: SRV records for XMPP over TLS                          PASSED

Informational tests:
Contact Addresses for reporting abuse                            PASSED
XEP-0156: Discovering Alternative XMPP Connection Methods (HTTP) PASSED
XEP-0077: In-Band Registration                                   PASSED

java -jar caas-app/target/caas-app.jar random@omemo.im 123
rocks.xmpp.core.XmppException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
	at rocks.xmpp.core.session.XmppSession.throwAsXmppExceptionIfNotNull(XmppSession.java:272)
	at rocks.xmpp.core.session.XmppClient.connect(XmppClient.java:251)
	at im.conversations.compliance.xmpp.TestExecutor.executeTestsFor(TestExecutor.java:35)
	at im.conversations.compliance.CommandLineLauncher.main(CommandLineLauncher.java:73)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
	at java.xml/com.sun.xml.internal.stream.XMLEventReaderImpl.peek(XMLEventReaderImpl.java:277)
	at rocks.xmpp.core.session.XmppStreamReader.lambda$startReading$90(XmppStreamReader.java:113)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by froghorn82** [comment]
So... whats the potential cause? Anyone know?

**Comment by licaon-kter** [comment]
Server config?

**Comment by RishiRaj22** [comment]
You do realise that the command line version does not have anything to do with the 'compliance server' as it runs locally on your machine or "you believe that someone who has access to your computer has removed the ability to test omemo.im for whatever reason that may be"

**Comment by iNPUTmice** [comment]
FWIW it’s your SRV records that are messed up. Port 443 on host `omemo.im` points to your website.

**Comment by froghorn82** [comment]
> FWIW it’s your SRV records that are messed up. Port 443 on host `omemo.im` points to your website.

@iNPUTmice, port 443 was SRV configured for XEP-0368 as per example: https://wiki.xmpp.org/web/Tech_pages/XEP-0368#DNS_setup
 
BTW, removing port 443 (which points to omemo.im; that is the xmpp server not just the website) from SRV made no difference.

**Comment by froghorn82** [comment]
Giggles and laughter but nothing has helped solve my problem.

**Comment by froghorn82** [comment]
> FWIW it’s your SRV records that are messed up. Port 443 on host `omemo.im` points to your website.

thank you @iNPUTmice

**Comment by froghorn82** [comment]
@iNPUTmice, My SRV records are now fixed and the local server testing is working all ok.

```
> ```
> java -jar caas-app/target/caas-app.jar random@omemo.im 123
> Server is running ejabberd 18.09
> 
> Compliance report for omemo.im
> XEP-0398: User Avatar to vCard-Based Avatars Conversion          PASSED
> XEP-0045: Multi-User Chat                                        PASSED
> XEP-0363: HTTP File Upload                                       PASSED
> XEP-0384: OMEMO Encryption                                       PASSED
> XEP-0313: Message Archive Management                             PASSED
> XEP-0313: Message Archive Management (for Multi-User Chat)       PASSED
> XEP-0065: SOCKS5 Bytestreams (Proxy)                             PASSED
> XEP-0280: Message Carbons                                        PASSED
> XEP-0352: Client State Indication                                PASSED
> XEP-0198: Stream Management                                      PASSED
> XEP-0115: Entity Capabilities                                    PASSED
> Roster Versioning                                                PASSED
> XEP-0191: Blocking Command                                       PASSED
> XEP-0163: Personal Eventing Protocol                             PASSED
> XEP-0357: Push Notifications                                     PASSED
> XEP-0160: Best Practices for Handling Offline Messages           PASSED
> XEP-0368: SRV records for XMPP over TLS                          PASSED
> 
> Informational tests:
> Contact Addresses for reporting abuse                            PASSED
> XEP-0156: Discovering Alternative XMPP Connection Methods (HTTP) PASSED
> XEP-0077: In-Band Registration                                   PASSED
```

Coming back to my main problem on compliance.conversations.im which you guys had a nice giggle over; 
1) I still can't test it on that site, still getting ParseError at [row,col]:[1,1] Message: Premature end of file.
2) When I try to register the server again on omemo.im with the same or new working credentials -  it always says ERROR: Credentials could not be verified
3) If I try to register another server that's present (like omemo.im in the list) to test from another domain it says: UPDATE: Credential already exists for server. Server will now be excluded from the public lists and tables ---->> Which is the expected output I would also expect for omemo.im.

So my problem in essence is still not solved. 
@licaon-kter @RishiRaj22 @iNPUTmice

**Comment by licaon-kter** [comment]
Maybe the broken SRVs were cached ?

**Comment by iNPUTmice** [comment]
> Maybe the broken SRVs were cached ?

Either that or we hard coded something in the caas to throw very weird error message when someone specifically tests `omemo.im` because we don’t like @froghorn82 and/or because we want to prevent users from using E2EE.

**Comment by licaon-kter** [comment]
Answer b)

**Comment by froghorn82** [comment]
Thanks guys, whatever it was it's all good and working now.
