### ISSUE TITLE
"Registration redirect to out of band URL" shows IBR passed

### ISSUE THREAD

**Issue by Perflyst** [iNPUTmice/caas#27]
With disabled ibr registration but enabled https://modules.prosody.im/mod_register_oob_url.html the XEP-0077 passes.

I do not allow IBR registration and just forward the user to the web registration formular.

**Comment by iNPUTmice** [comment]
I consider that correct behaviour. Clients will be able to provide a registration flow with that.

**Comment by Perflyst** [comment]
But they cannot register "in band" as you describe it at the compliance.

**Comment by Perflyst** [comment]
Thanks!
