### ISSUE TITLE
XEP-0368 test is false positive failing for kode.im

### ISSUE THREAD

**Issue by variablenix** [iNPUTmice/caas#29]
XMPP server: **Prosody 0.10.2**
XMPP over TLS ports: **443, 5223**

#### Relevant Prosody config
```
-- Ports
c2s_ports = { 5222, 443, 5223 } -- Listen on 443 and 5223 TLS as well as standard 5222
legacy_ssl_ports = { 5223 }
```
With the former deprecated compliance test `XEP-0368: SRV records for XMPP over TLS` passed on port 443. The corresponding SRV records for XMPP over TLS port 443 are still present. Now, with this current compliance test XEP-0368 is failing. To satisfy the current compliance test suite there are new SRV records for XMPP domain `kode.im` which are present for XMPP over TLS port 5223, respectively. Unfortunately the current compliance test is claiming XEP-0368 fails. This is not correct.

```
$ host -t srv _xmpps-client._tcp.kode.im
_xmpps-client._tcp.kode.im has SRV record 20 0 5223 io.kode.im.
_xmpps-client._tcp.kode.im has SRV record 15 5 443 venus.kode.im.
_xmpps-client._tcp.kode.im has SRV record 15 0 443 io.kode.im.
_xmpps-client._tcp.kode.im has SRV record 20 5 5223 venus.kode.im.
```
```
$ nc -z venus.kode.im 5223; nc -z io.kode.im 5223
Connection to venus.kode.im port 5223 [tcp/*] succeeded!
Connection to io.kode.im port 5223 [tcp/*] succeeded!
```
Judging by https://github.com/iNPUTmice/caas/issues/19 for the same XEP-0368 it would seem something with the current compliance test for XEP-0368 is not right.

**Comment by iNPUTmice** [comment]
I can connect on 5223 which is in your xmpps records. The test doesn’t check for 443 but for all xmpps records. If you remove the 5223 record it will fail.

**Comment by variablenix** [comment]
But the 5223 record has not been removed, so it should be pass not fail.

**Comment by iNPUTmice** [comment]
Are you able to establish a TLS connection on port 5223? Or log in with any XMPP client over that port?

**Comment by variablenix** [comment]
> Are you able to establish a TLS connection on port 5223? Or log in with any XMPP client over that port?

Establishing a TLS connection on port 5223 succeeds when testing with Adium. I can also telnet and netcat to 5223.

**Comment by variablenix** [comment]
FWIW I added port port 5223 to the `c2s_ports` list, but I don't think this is necessary. I haven't looked at the actual repo's code yet, but I'm wondering if there is some kind of cache that the compliance test saves and keeps referring to (maybe some kind of unexpired cache, but just a guess).

**Comment by iNPUTmice** [comment]
> FWIW I added port port 5223 to the c2s_ports

I’m not a Prosody expert but I don’t think this is how it works

**Comment by variablenix** [comment]
Yeah, I think you're right. I suppose I will just leave 5223 in the legacy ports section as instructed by the compliance suite. Even with 5223 only in legacy, the compliance test is not happy.

**Comment by iNPUTmice** [comment]
Please paste the output of `openssl s_client -connect venus.kode.im:5223 -servername kode.im`

**Comment by variablenix** [comment]
```
$ openssl s_client -connect venus.kode.im:5223 -servername kode.im
CONNECTED(00000005)
140736195621832:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.50.2/libressl/ssl/s23_clnt.c:565:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 334 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---
```
When checking on port 443 the proper certificate is returned. The strange part is a different XMPP server that the compliance suite shows as passing for XEP-0368 is not even listening on 5223 but only 443 for TLS. So is kode.im listening on 443 for TLS, but kode.im is failing for unknown reasons.

**Comment by variablenix** [comment]
I think if the test could check on 443 then it would all be fine. I'm not really sure why it only tests for 5223 as it is deprecated.

**Comment by iNPUTmice** [comment]
The test checks what ever you announce in your SRV records

**Comment by variablenix** [comment]
I experimented a bit more and well, this is really strange.

I added `im.koderoot.net` to the current compliance list as it was not present. The host `im.koderoot.net` has identical SRV records like `kode.im` and both use the same Prosody configuration including for their respective ports. Well, as it turns out `im.koderoot.net` is 100% compliant after running test #1 and having it added to the new compliant website list; however the compliance test continues to claim `kode.im` has not passed XEP-0368. This makes no sense as `kode.im` should then be at 100% because there is no real difference between the two except their domain name.

So I then attempted to _update_ the credentials for `kode.im` following https://compliance.conversations.im/add/ but kept getting a message **UPDATE: Credential already exists for server. Server will now be excluded from the public lists and tables**. Even if I _update_ the credentials on the server to the compliance testing account for `kode.im`, the same message is returned. How can it be possible that newly reset password credentials are already stored in the compliance database? So ultimately I cannot get the compliance test to cooperate and update appropriately. 

**Suggestion:** Perhaps `kode.im` can be completely removed from the database and then I can re-add it back -- treating `kode.im` like it has never been been added to the new compliance database just how `im.koderoot.net` was not previously added but still managed to be 100% compliant on the first run.

**Comment by licaon-kter** [comment]
@variablenix Why not test locally first, compile `caas` ?

**Comment by variablenix** [comment]
@licaon-kter I think I will attempt that next and report back.

**Comment by variablenix** [comment]
I ran the test locally and got the same result, sadly.

`XEP-0368: SRV records for XMPP over TLS                          FAILED`

Not really sure what else to do. It's a bit annoying as it doesn't make sense why `kode.im` is failing yet the 2nd domain is fine, but I think I'll not worry about it anymore. Thanks all for your help.
