### ISSUE TITLE
Feature request: Sort server names alphabetically

### ISSUE THREAD

**Issue by Echolon** [iNPUTmice/caas#30]
Hi,

often enough, I search of a specific server by name. The easierst thing would be to be able to sort the server name list on the left the same way as the other columns. Another problem is that if I use Ctrl + F the the results are highlighted but I have to scoll down myself. So the screen does not jump downwards (or upwards) to the result.

Using: Firefox 63.0.1 (64-bit)

(@RishiRaj22 )

Anyway, thanks - nice website!

**Comment by mulles** [comment]
Work around: 

You can use Compatibility view button on the bottom of the page: 

![screenshot from 2018-11-22 12-48-04](https://user-images.githubusercontent.com/13488510/48901245-1498f700-ee55-11e8-9e64-fc633b11067a.png)


Then you can use your browsers search option to find the server, without the need to manually scroll done.

**Comment by RishiRaj22** [comment]
That has always been on my todo list. I'll hopefully have some free time after a couple of weeks to get it done.
