### ISSUE TITLE
Give me some instructions on how to implement the profiles which are currently not supported

### ISSUE THREAD

**Issue by devurandom** [iNPUTmice/caas#36]
The readme says:
> This app won't just help you to assess if your server supports those compliance profiles, but also give you some instructions on how to implement the profiles which are currently not supported (if you are using popular server softwares)

However, when running the app, I just get the information that certain XEPs "FAILED", but no indication on what part of it failed or how to fix it. The app also notices that "Server is running Prosody 0.10.2", which I guess qualifies as "popular server software" as mentioned in the readme.

There is no `-h` or `--help` flag on the app to show me further instructions or command line arguments, either.

**Comment by RishiRaj22** [comment]
The help option is only available in the web service mode. However, you can manually find it in caas-web/src/main/resources/help/prosody/test_name.md
