### ISSUE TITLE
Accessibility: server overview is unfriendly to users with red-green colour deficiency

### ISSUE THREAD

**Issue by mwild1** [iNPUTmice/caas#40]
The server status for each test is currently represented by a red block or a green block. For a small number of users this can make it very hard to perceive the difference between the two states. For more information see https://en.wikipedia.org/wiki/Color_blindness#Red-green_color_blindness

Possible solutions would be adding some text (with sufficient contrast) or replacing the boxes with icons, etc.

**Comment by RishiRaj22** [comment]
There already is an option for colorblind mode at the bottom

**Comment by licaon-kter** [comment]
Why not use the "Colourblind" mode link?

**Comment by mwild1** [comment]
Ha, great news that this is implemented. Clearly it's not very visible though. I feel making it accessible by default would be a far better approach.
