### ISSUE TITLE
Test for XEP-0384 failes with a Database failure

### ISSUE THREAD

**Issue by arendtio** [iNPUTmice/caas#42]
Last week I tried to get a 100% score for my server. So far I didn't manage to achieve that as the test for OMEMO (XEP-0384) keeps failing and I don't know why (it seems to be related to the line `node.delete().get()`). Because the test causes a 'Database failure' on the server side, my first intuition was to create a bug for ejabberd. However, @licaon-kter advised me to open an issue here.

In order to not duplicated the content, I will keep it to the minimum here. The other details are listed in the [ejabberd bug](https://github.com/processone/ejabberd/issues/2726).

Server:
- ejabberd 18.12 on Arch Linux installed via pacakage manager (pacman)
- Mnesia Database

**Comment by iNPUTmice** [comment]
This has nothing to do with the tester.
