### ISSUE TITLE
http_upload CORS headers: Case insensitivity

### ISSUE THREAD

**Issue by ThomasLeister** [iNPUTmice/caas#43]
The check for http_upload CORS HTTP headers seems to check with case sensitivity on. That means all-lowercase headers will not be recognized, although valid:

"Field names are case-insensitive."  - https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

Some frameworks / libraries automaticalls convert headers to lowercase-only versions, such as the Golang internal HTTP library. 

Result: The CORS check fails although HTTP headers are valid. It would be nice to have this fixed in the next version :-)

**Comment by ApoRes1337** [comment]
+1 for fix it pls
