### ISSUE TITLE
Compatibility with Tigase XMPP Server (e.g. tigase.im)

### ISSUE THREAD

**Issue by woj-tek** [iNPUTmice/caas#45]
I check result page for Tigase XMPP Server (i.e. https://compliance.conversations.im/server/tigase.im/ ) and test tool reported a couple of failures. Apart from features not supported (e.g.: OMEMO) following features are implemented and tested (hence failing test are surprising):
    * XEP-0115: Entity Capabilities 
    * XEP-0357: Push Notifications
    * XEP-0163: Personal Eventing Protocol 
    * XEP-0313: Message Archive Management (for Multi-User Chat) 
    * XEP-0153: vCard-Based Avatar (MUC) -- I'm not sure about "MUC" suffix but this is also supported.

Push test (https://github.com/iNPUTmice/caas/blob/master/caas-app/src/main/java/im/conversations/compliance/xmpp/tests/Push.java) seems to oly test for `urn:xmpp:push:0` and even though server includes it, as per specification, in features, the tool still reports failure:
```xml
<iq to='tigase.im'
    id='x13'
    type='get'>
  <query xmlns='http://jabber.org/protocol/disco#info'/>
</iq>
<r xmlns="urn:xmpp:sm:3"/>

<a xmlns="urn:xmpp:sm:3" h="66"/>

<iq from="tigase.im" id="x13" type="result" to="wojtek@tigase.im/firefly/psi+/green">
<query xmlns="http://jabber.org/protocol/disco#info">
<identity category="component" name="Tigase ver. 8.0.0-RC1" type="im"/>
<identity category="server" name="Tigase ver. 8.0.0-RC1" type="im"/>
<feature var="http://jabber.org/protocol/commands"/>
<feature var="urn:xmpp:carbons:2"/>
<feature var="http://jabber.org/protocol/stats"/>
<feature var="vcard-temp"/>
<feature var="jabber:iq:auth"/>
<feature var="http://jabber.org/protocol/amp"/>
<feature var="msgoffline"/>
<feature var="urn:xmpp:push:0"/>
<feature var="tigase:push:away:0"/>
<feature var="http://jabber.org/protocol/disco#info"/>
<feature var="http://jabber.org/protocol/disco#items"/>
<feature var="urn:xmpp:blocking"/>
<feature var="urn:xmpp:ping"/>
<feature var="urn:ietf:params:xml:ns:xmpp-sasl"/>
<feature var="http://jabber.org/protocol/pubsub"/>
<feature var="http://jabber.org/protocol/pubsub#owner"/>
<feature var="http://jabber.org/protocol/pubsub#publish"/>
<identity category="pubsub" type="pep"/>
<feature var="urn:xmpp:archive:auto"/>
<feature var="urn:xmpp:archive:manage"/>
<feature var="jabber:iq:roster"/>
<feature var="jabber:iq:roster-dynamic"/>
<feature var="urn:xmpp:mam:1"/>
<feature var="jabber:iq:version"/>
<feature var="urn:xmpp:time"/>
<feature var="jabber:iq:privacy"/>
<feature var="urn:ietf:params:xml:ns:xmpp-bind"/>
<feature var="http://jabber.org/protocol/commands"/>
<feature var="urn:ietf:params:xml:ns:vcard-4.0"/>
<feature var="jabber:iq:private"/>
<feature var="urn:ietf:params:xml:ns:xmpp-session"/>
</query>
</iq>
```

I checked the source for MUC MAM test and it has following line https://github.com/iNPUTmice/caas/blob/master/caas-app/src/main/java/im/conversations/compliance/xmpp/tests/MamMuc.java#L54 and it looks that the tool is skewed towards ejabberd:
```java
final DataForm.Field mam = form.findField("mam"); //ejabberd community
final DataForm.Field roomConfigMam = form.findField("muc#roomconfig_mam"); //ejabberd SaaS
final DataForm.Field roomConfigEnable = form.findField("muc#roomconfig_enablearchiving");
```
I'd argue that tests should only adhere to the specification defined in XEPs: https://xmpp.org/extensions/xep-0313.html#support

-------

There is also less-technical aspect: about section states: 
> Picking the right extensions to implement or enable isn't always easy. For this reason the XSF has published `XEP-0387 XMPP Compliance Suites 2018` listing the most important extensions to date. This app won't just help you to assess if your server supports those compliance profiles(and more), but also give you some instructions on how to implement the profiles which are currently not supported. 
Which my suggest, that the app tests for compatibility with mentioned compliance suite, however:
* XEP-0398: User Avatar to vCard-Based Avatars Conversion 
* XEP-0384: OMEMO Encryption 
are not part of this XEP, thus I would argue that they should be moved to "Results for informational tests" part to avoid confusion. It would also be great to reflect that on the main page where `Compliance` column counts all test that could lead to incorrect conclussions regarding actual compliance with _Compliance Suites _

**Comment by iNPUTmice** [comment]
The push test tests for the feature on the account not the server.
The MAM test not only tests for the vendor specific data form field but
primarily for the mam feature on the room jid which tigase apparently
doesn't advertise. Feel free to let me know how to figure out if a given
room supports MAM on a tigase server.

**Comment by woj-tek** [comment]
Thank you - I entered two issues to tigase bugtrack to correct those.

What about remaining XEPs? Caps, PEP and vCards?

And the suggestion to distinguish results better?

**Comment by iNPUTmice** [comment]
PEP might fail because of a missing identity? Just guessing. The caps test is testing for the <c/> stream feature iirc. Vcard is testing for the vcard feature on a room.

**Comment by woj-tek** [comment]
> PEP might fail because of a missing identity? Just guessing.

Spot on

> The caps test is testing for the stream feature iirc.

Thank you - we will add it

> Vcard is testing for the vcard feature on a room.

Hmm, I would like to propose splitting this test - to test support for vcard (and avatar) in general and explicitly for MUC (which may be independent from main server and is rather specific) -- what do you think?

**Comment by iNPUTmice** [comment]
> Hmm, I would like to propose splitting this test - to test support for vcard (and avatar) in general and explicitly for MUC (which may be independent from main server and is rather specific) -- what do you think?

To be clear that test is *only* testing for vcard on a muc room. Not vcard on the account or server. So it wouldn’t be splitting but rather creating an additional test for vcard on account. That would be a rather boring test I assume. Most servers will support that and I think the general recommendation for clients is to use PEP anyway. Also testing for vcard on the account is sort of implied by the vcard conversion test.

I think there has been a consensus at the summit to eventually support PEP on the room so the room could do PEP avatars instead of vcards. So vcards on a room might only be a momentary feature anyway. Either way uploading 'room avatars' is a feature people want and that's why the test exists. vcard on the account on the other hand is relatively boring.

**Comment by woj-tek** [comment]
> To be clear that test is _only_ testing for vcard on a muc room. Not vcard on the account or server. So it wouldn’t be splitting but rather creating an additional test for vcard on account.

Correct 

> That would be a rather boring test I assume. Most servers will support that and I think the general recommendation for clients is to use PEP anyway. Also testing for vcard on the account is sort of implied by the vcard conversion test.

It is _sorta implied_ however this brings me back to first point - the test suite implies that it performs testing against Compliance Suite, and with this selectivity (avatars only for MUC, avatar conversion not being even part of the compliance suite) it skews the perception of what is actually supported. 
Tigase scored only ~50% which may indicate that it misses half of the features required by the suite which isn't true.
You stated, that testing for avatars may be boring - maybe it is, but it gives better overview of what's to be expected from server and it's adherence to the specification. What's more - for MAM there is separate test for MUC.

> I think there has been a consensus at the summit to eventually support PEP on the room so the room could do PEP avatars instead of vcards. So vcards on a room might only be a momentary feature anyway. Either way uploading 'room avatars' is a feature people want and that's why the test exists. vcard on the account on the other hand is relatively boring.

Creating such test is/was easy (would you accept PR?) and it could be _for the time being_, until PEP based avatars are finalised and more popular - the more test the better IMHO :-)

**Comment by iNPUTmice** [comment]
I’m closing here. Whether or not vcard detection is a useful addition can be discussed in the corresponding PR; all other questions have been answered
