### ISSUE TITLE
XEP-0156: Require CORS for host-meta file

### ISSUE THREAD

**Issue by wiktor-k** [iNPUTmice/caas#49]
I propose adding an additional check to [XEP-0156: Discovering Alternative XMPP Connection Methods](https://github.com/iNPUTmice/caas/blob/master/caas-app/src/main/java/im/conversations/compliance/xmpp/tests/AlternateConnections.java#L23) test that will fail the test if `Access-Control-Allow-Origin: *` header is not present in response. The test is described as "Allows web clients to discover connections methods" but unfortunately without CORS web clients hosted on foreign domains (such as [Converse.js](https://github.com/conversejs/converse.js/issues/129)) won't be able to discover it.

Recently the [implementation notes for XEP-0156](https://xmpp.org/extensions/xep-0156.html#impl) were extended to suggest adding this header.

For the record, conversations.im would pass this test:

```
$ curl -I https://conversations.im/.well-known/host-meta
HTTP/1.1 200 OK
Server: nginx/1.10.3
...
ETag: "5bfc0955-11a"
Access-Control-Allow-Origin: *
```

There are two additional checks that could be performed:
  1. Issuing HTTP OPTIONS request on endpoints mentioned in host-meta and seeing if they also are CORS-enabled
  2. Checking if the endpoints mentioned use secure connections (`https` instead of `http` and `wss` instead of `ws`). (I've seen some servers in compliance tester with these issues).

I can work on a PR if this has a chance of being merged.

**Comment by wiktor-k** [comment]
> at some point we really need to do something about the home screen UI if we keep adding more and more tests

Agreed although I don't have a solution for that one. Maybe display just %s or SSLLabs-like grading system? SSLLabs grades and percents are carefully thought of to encourage best-practices (they are *not* direct "number of features" to letter transformation).

**Comment by iNPUTmice** [comment]
fixed by your now merged PR

**Comment by wiktor-k** [comment]
Okay. If you don't mind I'll file a new PR that checks if the endpoints mentioned in `host-meta` also have appropriate headers set. (I wanted to keep the last one small).

Glad to see it's already operational on http://compliance.conversations.im

**Comment by iNPUTmice** [comment]
Maybe you can do some additional sanity checking on the endpoint as well. See if there is actually a BOSH or websocket listening. Similar to how we do it for TLS https://github.com/iNPUTmice/caas/blob/master/caas-app/src/main/java/im/conversations/compliance/xmpp/tests/XmppOverTls.java#L46-L63 (nothing fancy; just a quick check so people don’t just point it to a random website.)

**Comment by wiktor-k** [comment]
Yes, good idea about splitting it. Currently CAAS reports whether the test passed or not but if the test has multiple things to check it's not obvious what went wrong (SSLLabs I believe has additional info about errors encountered).
