### ISSUE TITLE
Detection of SCRAM-SHA-256(-PLUS) server support [and SCRAM-SHA-1(-PLUS) in the same time]

### ISSUE THREAD

**Issue by Neustradamus** [iNPUTmice/caas#62]
It is possible to add a new test for have information about SCRAM-SHA-256(-PLUS) support?
In the same time it is possible to have in the same time for SCRAM-SHA-1(-PLUS).

A lot of people forget the security importance.

Thanks in advance.

**Comment by iNPUTmice** [comment]
We technically could but since server admins usually take the compliance tester as a recommendation on what to configure I don’t think we should

* -PLUS is not specified to work with TLSv1.3
* -SHA-256 is not significantly more secure than -SHA-1 (or -SHA1 isn’t insecure per se)

**Comment by Neustradamus** [comment]
What we must have to be more secure?
