### ISSUE TITLE
Feature Request: add option to rerun particular Test

### ISSUE THREAD

**Issue by aslmx** [iNPUTmice/caas#64]
Right now you can manually re run a test, but only - as it seems - the full test... which does not have a progress indication (see other issue ;)).

It would be very nice to have a possibility to re-run ONE particular Test, if you changed the config to comply, you maybe just want to know whether one particular test is now passed.

**Comment by RishiRaj22** [comment]
That was something I had initially planned for. But the tests practically take the majority of time logging in. Running each particular test requires just few milliseconds of overhead after that(barring a few tests which take a bit longer). So, adding either a progress bar or adding options to rerun a particular test are overkill at the moment.
