### ISSUE TITLE
Dockerize the project

### ISSUE THREAD

**Issue by immanuelfodor** [iNPUTmice/caas#66]
Hi, I've found it unnecessary to setup the build env on my computer as I only wanted to try out the tool locally, so I created the below `Dockerfile`:

```bash
cat <<EOF > Dockerfile
FROM alpine/git
WORKDIR /app
RUN git clone https://github.com/iNPUTmice/caas.git

FROM maven:3.6.1-jdk-11
WORKDIR /app
COPY --from=0 /app/caas /app
RUN mvn package

FROM openjdk:11-jdk
WORKDIR /app
COPY --from=1 /app/caas-app/target/caas-app.jar /app
COPY --from=1 /app/caas-web/target/caas-web.jar /app
COPY --from=1 /app/caas-annotations/target/caas-annotations-0.0.1.jar /app
EXPOSE 4567
RUN echo '{ "ip": "0.0.0.0", "testRunInterval": 5 }' > config.json
CMD ["java", "-jar", "caas-web.jar"]
EOF

sudo docker build -t caas:latest .
sudo docker run --rm --name caas -p 8000:4567 caas:latest
```

The site loads on http://localhost:8000 but it doesn't seem to do anything other than spinning the loader and waiting for the test to complete, so I thought maybe the websocket needs HTTPS. I tried to use `ngrok`:

```bash
# another terminal
sudo docker exec -it caas bash
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
unzip ngrok-stable-linux-amd64.zip
./ngrok http 4567
```

The page at this point is available on https://some-random-string.ngrok.io but still doesn't seem to work. There are some warnings on the first console:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.sql2o.reflection.MethodGetter (file:/app/caas-web.jar) to method java.lang.String.getBytes(byte[],int,byte)
WARNING: Please consider reporting this to the maintainers of org.sql2o.reflection.MethodGetter
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Maybe this causes the problem?
I also tried installing `sqlite3` with `apt update && apt install sqlite3` and then look around in the DB file. Credentials are saved, and there is the server with its XMPP version but every other table is empty.
Tried running the CLI app inside the container, too, it outputs the server version and then seems to hang.
Can you help with providing a working `Dockerfile` or pointing in the right direction how can I make this work?

**Comment by iNPUTmice** [comment]
I don’t think what ever you are running into has anything to do with docker. And our issue tracker is probably not the right place for getting help with docker.
I think some of the tests don’t have proper network time outs which can be problem in filtered network environments and cause the tests to run seemingly for ever.

**Comment by immanuelfodor** [comment]
Wow, that was quick :astonished: Okay, no problem, it seems to run forever with the online version, too, but I hoped I can get results locally. Maybe others can benefit from the shared snippets above. Have a nice day!

**Comment by iNPUTmice** [comment]
If you have entered credentials into the online version anyway mind sharing the domain so I can look into addressing the time out issues?

**Comment by immanuelfodor** [comment]
Well, it's https://compliance.conversations.im/live/hl.dip.fodor.it/ and still spinning. The funny thing is that [XMPPoke](https://github.com/xmpp-observatory/xmppoke) gives 100/100/100/90 security results (-10p for supporting some 128 bit ciphers for compatibility), I just wanted to see if I need to add some more plugins for better compliance on the protocol level. I can see the tool authing successfully in the server logs with `TLSv1.2 with DHE-RSA-AES256-GCM-SHA384` so it can't be that it can't look around.

**Comment by iNPUTmice** [comment]
I've implemented proper timeouts in one of the tests and now the results come in reasonably fast.

**Comment by immanuelfodor** [comment]
Now, it works like a charm both locally in Docker with the above `Dockerfile` and online. Thank you for the fix!
