### ISSUE TITLE
[proposal] Add Prosody ports for XEP-0156 (http) test

### ISSUE THREAD

**Issue by moppman** [iNPUTmice/caas#7]
https://github.com/iNPUTmice/caas/blob/3e2385a77b5c0f4ea1608459094e648e26f79c14/caas-app/src/main/java/im/conversations/compliance/xmpp/tests/AlternateConnections.java#L48

This tests only standard ports 80 or 443, so maybe you could add ports 5280/5281 as fallback? Those are the default ports for Prosody's built-in http server which is widely used.

**Comment by iNPUTmice** [comment]
This would defeat the purpose as a web client wouldn't be able to discover
them either.

**Comment by moppman** [comment]
Yep, you're right.
