### ISSUE TITLE
Add server: Pasting password results in empty password message

### ISSUE THREAD

**Issue by vanitasvitae** [iNPUTmice/caas#71]
When copy pasting credentials while adding a server, the UI states that the password is empty, while infact the field is filled. Adding and removing a character with the keyboard fixes the error message.

**Comment by RishiRaj22** [comment]
Hi, sorry for late response. Which browser and OS are you using, because it works fine for me on Firefox and Chromium in Linux?

**Comment by vanitasvitae** [comment]
Firefox on Debian. Strange...
The issue still happens for me. Note that it only happens when pasting text via the right click context menu.
