### ISSUE TITLE
Problems with XEP-0156: Discovering Alternative XMPP Connection Methods (HTTP)

### ISSUE THREAD

**Issue by JonnyTischbein** [iNPUTmice/caas#8]
I'm in trouble passing the last test XEP-0156 and the alternative XMPP connection via http(s).

Currently prosody runs with the module bosh locally on port 5280/5281. NGINX is proxying the request from `https://domain.tld/http-bind` to `localhost:5280/http-bind`.
Every http request will be redirected to https with HTTP Status 301.
The same is the case for  `/.well-kown/host-meta` [1] and  `/.well-kown/host-meta.json` [2]

If I'm getting the source code right the script is checking for http and https. Can it handle the redirecting to https or do I need to make it accessable without https and if yes, why so?

[1] -

```
<?xml version='1.0' encoding=utf-8'?>
 <XRD xmlns='http://docs.oasis-open.org/ns/xri/xrd-1.0'>
  <Link rel="urn:xmpp:alt-connections:xbosh"
        href="https://domain.tld/http-bind" />
  <Link rel="urn:xmpp:alt-connections:websocket"
        href="wss://domain.tld/http-bind" />
 </XRD>
```

[2] -
```
{
  "links": [
    {   
      "rel": "urn:xmpp:alt-connections:xbosh",
      "href": "https://domain.tld/http-bind"
    },  
    {   
      "rel": "urn:xmpp:alt-connections:websocket",
      "href": "wss://domain.tld/http-bind"
    },  
  ]
}
```

**Comment by JonnyTischbein** [comment]
I still don't get it to work.

Now I added Ports in the host-meta files and run websocket and bosh parallel.

- Bosh: https://domain.tld/http-bind with href="https://domain.tld:443/http-bind" in host-meta
- Websocket: https://domain.tld/xmpp-websocket with href="wss://domain.tld:443/websoket" in host-meta

I'm I missing anything ? Looking at [https://github.com/iNPUTmice/caas/blob/master/caas-app/src/main/java/im/conversations/compliance/xmpp/tests/AlternateConnections.java](https://github.com/iNPUTmice/caas/blob/master/caas-app/src/main/java/im/conversations/compliance/xmpp/tests/AlternateConnections.java)

- files providing "urn:xmpp:alt-connections:xbosh", "urn:xmpp:alt-connections:websocket"
- reachable at /.well-known/host-meta and /.well-known/host-meta.json
- conatining rel and href argument
- port is set
- connection test works manually
Result for Bosh
```
    <html><body>
    <p>It works! Now point your BOSH client to this URL to connect to Prosody.</p>
    <p>For more information see <a href="http://prosody.im/doc/setting_up_bosh">Prosody: Setting up BOSH</a>.</p>
    </body></html>
```

Result for Websocket
```
    <!DOCTYPE html><html><head><title>Websocket</title></head><body>
    <p>It works! Now point your WebSocket client to this URL to connect to Prosody.</p>
    </body></html>
```

**Comment by iNPUTmice** [comment]
No idea. If you want you can send me a test account on your server (so I can run the Compliance Tester without much effort) and I can step through the code see where it fails. Contact information is on my website.

**Comment by mightyBroccoli** [comment]
I also had some issues with the compliance to that. I used the xml/ json templates from the XEP and only added my server info.
The XEP suggests to add the xml header to the file like you did in your example, but only if I remove the header the xml is recognized by the test suite. I am not sure if that is truly the reason but at least on 2 different servers this solution did work. 
```
<XRD xmlns='http://docs.oasis-open.org/ns/xri/xrd-1.0'>
	<Link rel="urn:xmpp:alt-connections:xbosh"
		href="https://magicbroccoli.de/http-bind" />
	<Link rel="urn:xmpp:alt-connections:websocket"
		href="wss://magicbroccoli.de/xmpp-websocket" />
</XRD>
```
For the json file you may remove the `,` after the last array. With the comma in place the json is not able to be parsed, remove it and you are done.

**Comment by JonnyTischbein** [comment]
Right!

That solved my problem too. The xml file is also incorrect.

In the first the line is a ````'```` missing:

> [1] -
> 
> <?xml version='1.0' encoding=utf-8'?>
