### ISSUE TITLE
Implements API to get a JSON-Array of all Servers

### ISSUE THREAD

**Issue by genofire** [iNPUTmice/caas#9]
Something like:
HTTP-GET `/server.json`
With Result:
```json
[
{"domain": "404.city", "lastresult": "17/17", "lastresult_percent": "100"},
{"domain": "conversations.im", "lastresult": "17/17", "lastresult_percent": "100"},
...
]
```

**Comment by genofire** [comment]
So my idea was just to have the `domain` and summarized last state of check - think it is enought.

Another API could be HTTP-GET `/server/:domain.json` (e.g. `/server/covnersations.im.json`) with more/every detail. (Which could be discussed in another issue)

**Comment by iNPUTmice** [comment]
Yes I got how you think the output should look like. But please describe the use case.

**Comment by genofire** [comment]
to request a list xmpp-servers and how go they supported is.
Thats usefull in clients to give a list of servers during registation and login process (maybe as autocompletion)

**Comment by iNPUTmice** [comment]
And probably only server that are 100% compliant.

However let the record show that automatically adding servers to a list of recommended servers just because they are 100% compliant and offer in band registration is a terrible idea. That is in no way shape or form an indication of quality.

**Comment by licaon-kter** [comment]
Comparing to the other way of adding them now and hoping for the best in the future, downloading the list on account creation is a big step forward.

**Comment by genofire** [comment]
Thankyou @RishiRaj22 - when does it deployed?

**Comment by genofire** [comment]
done - thx
